services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db

    ports:
      - "${MONGO_DB_PORT}:27017"
    volumes:
      - mongo:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet 1
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - microservices
#
  postgresql:
    image: postgres:latest
    container_name: postgresql_db
    ports:
      - "${POSTGRESQL_DB_PORT}:5432"
    volumes:
      - postgres:/data/postgres
    restart: always
    environment:
#      - POSTGRES_USER=${POSTGRESQL_DB_USERNAME}
#      - POSTGRES_PASSWORD=${POSTGRESQL_DB_PASSWORD}
      - POSTGRES_USER=${VEHICULO_DB_USERNAME}
      - POSTGRES_PASSWORD=${VEHICULO_DB_PASSWORD}
      - POSTGRES_DB=${VEHICULO_DB_NAME}
      - PGDATA=/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${VEHICULO_DB_USERNAME} -d ${VEHICULO_DB_PASSWORD}'"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - microservices
#
  oracledb:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle_db
    ports:
      - "${ORACLE_DB_PORT_1}:1521"
      - "${ORACLE_DB_PORT_2}:5500"
    volumes:
      - ./Oracle_Sql/init.sql:/opt/oracle/scripts/startup/01-init.sql
      - oracle:/opt/oracle/oradata
    restart: always
    environment:
      - ORACLE_CHARACTERSET=${ORACLE_DB_CHARACTERSET}
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_USER=system  
      - ORACLE_PWD=pass
    networks:
       - microservices
#
  mysqldb:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "${MYSQL_DB_PORT}:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: parking
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    networks:
      - microservices
#
  config-server:
    build: 
      context: .
      dockerfile: ./config-server/Dockerfile
    container_name: config-server
    ports:
      - "${CONFIG_SERVER_PORT}:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://config-server:${CONFIG_SERVER_PORT}/actuator/health"]
      interval: 20s
      timeout: 3s
      retries: 5
    restart: on-failure
    networks:
      - microservices
#  
  discovery-server:
    build: 
      context: .
      dockerfile: ./discovery-server/Dockerfile
    container_name: discovery-server
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - "${EUREKA_SERVER_PORT}:8761"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:${CONFIG_SERVER_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery-server:${EUREKA_SERVER_PORT}/actuator/health"]
      interval: 20s
      timeout: 3s
      retries: 5
    restart: on-failure
    networks:
      - microservices
#
  cliente-microservice:
    build: 
      context: .
      dockerfile: ./microservices/cliente-microservice/Dockerfile
    container_name: cliente-microservice
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      mongodb:
        condition: service_started
    ports:
      - "${CLIENTE_MICROSERVICE_PORT}:8091"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:${CONFIG_SERVER_PORT}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:${EUREKA_SERVER_PORT}/eureka/
      - SPRING_MONGODB_URI=mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongodb:${MONGO_DB_PORT}/${CLIENTE_DB_NAME}?authSource=admin
    networks:
      - microservices
#
  vehiculo-microservice:
    build:
      context: .
      dockerfile: ./microservices/vehiculo-microservice/Dockerfile
    container_name: vehiculo-microservice
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      postgresql:
        condition: service_started
    ports:
      - "${VEHICULO_MICROSERVICE_PORT}:8092"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:${POSTGRESQL_DB_PORT}/${VEHICULO_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${VEHICULO_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${VEHICULO_DB_PASSWORD}
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:${CONFIG_SERVER_PORT}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:${EUREKA_SERVER_PORT}/eureka/
    networks:
      - microservices
#
  historico-microservice:
    build:
      context: .
      dockerfile: ./microservices/historico-microservice/Dockerfile
    container_name: historico-microservice
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
#      mysqldb:
#        condition: service_healthy
      oracledb:
        condition: service_healthy
    ports:
      - "${HISTORICO_MICROSERVICE_PORT}:8093"
    environment:
#      - SPRING_DB_URL=jdbc:mysql://mysqldb:3306/parking?createDatabaseIfNotExist=true&serverTimezone=UTC
#      - SPRING_DB_USER_NAME=root
#      - SPRING_DB_PASSWORD=pass
      - SPRING_DB_URL=jdbc:oracle:thin:@oracledb:1521:xe
      - SPRING_DB_USER_NAME=parking
      - SPRING_DB_PASSWORD=pass
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:${CONFIG_SERVER_PORT}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:${EUREKA_SERVER_PORT}/eureka/
    networks:
      - microservices
#
#  diccionario-microservice:
#    build:
#      context: .
#      dockerfile: ./microservices/dicionario-microservice/Dockerfile
#    container_name: diccionario-microservice
#    depends_on:
#      config-server:
#        condition: service_healthy
#      discovery-server:
#        condition: service_healthy
#      mysqldb:
#        condition: service_healthy
#    ports:
#      - "${DICCIONARIO_MICROSERVICE_PORT}:8094"
#    environment:
#      - SPRING_DB_URL=jdbc:mysql://mysqldb:3306/parking?createDatabaseIfNotExist=true&serverTimezone=UTC
#      - SPRING_DB_USER_NAME=root
#      - SPRING_DB_PASSWORD=pass
#      - SPRING_CONFIG_IMPORT=configserver:http://config-server:${CONFIG_SERVER_PORT}
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:${EUREKA_SERVER_PORT}/eureka/
#    networks:
#      - microservices
#
  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    container_name: gateway-server
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    ports:
      - "${API_GATEWAY_PORT}:8222"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:${CONFIG_SERVER_PORT}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:${EUREKA_SERVER_PORT}/eureka/
    networks:
      - microservices


volumes:
  mongo:
  postgres:
  oracle:
  mysql:

networks:
  microservices:
    driver: bridge